version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDPANDA_BROKERS=redpanda:9092
    depends_on:
      - redpanda
    restart: unless-stopped
    command:
      - uv
      - run
      - app.py
  redpanda:
    image: redpandadata/redpanda:latest
    ports:
      - "9092:9092"  # Kafka API
      - "9644:9644"  # Admin API
    environment:
      - REDPANDA_RPC_SERVER_LISTEN_ADDR=0.0.0.0
      - REDPANDA_KAFKA_ADDRESS=0.0.0.0
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=0.0.0.0:9092
      - --advertise-kafka-addr=redpanda:9092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda:33145

  redpanda-console:
    image: redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      - REDPANDA_BROKERS=redpanda:9092
    depends_on:
      - redpanda

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
      - "9009:9009"  # Interserver communication
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config:/etc/clickhouse-server/config.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - redpanda
    restart: unless-stopped
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    entrypoint: >
      bash -c "
        /entrypoint.sh &
        sleep 10 && /etc/clickhouse-server/config.d/init-script.sh &
        wait
      "

volumes:
  redpanda_data:
  clickhouse_data: